spring:
  application:
    name: OmniHub

  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl
    cache: false
    expose-request-attributes: true
    expose-session-attributes: true

  devtools:
    restart:
      enabled: true

  datasource:
    master:
      url: jdbc:postgresql://localhost:5432/omnihub
      username: wantana
      password: wantana2026!@#
      driver-class-name: org.postgresql.Driver
      hikari:
        minimum-idle: 5
        maximum-pool-size: 20
        idle-timeout: 300000
        max-lifetime: 1800000
        connection-timeout: 30000
        pool-name: OminiHubPool
    slave:
      url: jdbc:postgresql://localhost:5432/omnihub
      username: wantana
      password: wantana2026!@#
      driver-class-name: org.postgresql.Driver
      hikari:
        minimum-idle: 5
        maximum-pool-size: 20
        idle-timeout: 300000
        max-lifetime: 1800000
        connection-timeout: 30000
        pool-name: OminiHubPool

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      default_schema: public
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
    locations:
      - classpath:db/migration/core
      - classpath:db/migration/iam
      - classpath:db/seed/core
      - classpath:db/seed/iam

jwt:
  secret: 1234567890123456789012345678901234567890123456789012345678901234
  expiration: 86400000

server:
  port: 8080
  forward-headers-strategy: framework