spring:
  application:
    name: OmniHub

  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl
    cache: false
    expose-request-attributes: true
    expose-session-attributes: true

  devtools:
    restart:
      enabled: true

  datasource:
      url: jdbc:postgresql://postgres:5432/koffeedb
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

server:
  port: 8080
  forward-headers-strategy: framework