spring:
  application:
    name: OmniHub

  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:8080

  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl
    cache: false
    expose-request-attributes: true
    expose-session-attributes: true

  devtools:
    restart:
      enabled: true

  datasource:
    master:
      url: jdbc:postgresql://localhost:5432/myappdb
      username: kothein
      password: postgres
      driver-class-name: org.postgresql.Driver
    slave:
      url: jdbc:postgresql://localhost:5432/myappdb
      username: kothein
      password: postgres
      driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migratio

server:
  port: 8080
  forward-headers-strategy: framework