CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE SCHEMA IF NOT EXISTS iam;

CREATE SCHEMA IF NOT EXISTS core;

CREATE SCHEMA IF NOT EXISTS inventory;

CREATE SCHEMA IF NOT EXISTS restaurant;

CREATE SCHEMA IF NOT EXISTS electronic;

CREATE SCHEMA IF NOT EXISTS coffeeshop;

CREATE SCHEMA IF NOT EXISTS minimart;

CREATE SCHEMA IF NOT EXISTS bakery;

CREATE SCHEMA IF NOT EXISTS pharmacy;

CREATE SCHEMA IF NOT EXISTS hotel;

CREATE SCHEMA IF NOT EXISTS bookstore;

CREATE SCHEMA IF NOT EXISTS petshop;