name: omnihub

services:

  postgres:
    build:
      context: ../postgres
    container_name: omnihub

    environment:
      POSTGRES_DB: omnihub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql

  app:
    build:
      context: ../..
      dockerfile: devops/app/Dockerfile
    container_name: omnihub-app

    depends_on:
      - postgres

    environment:
      SPRING_PROFILES_ACTIVE: docker

    ports:
      - "8080:8080"

  nginx:
    build:
      context: ../nginx

    container_name: omnihub-nginx

    depends_on:
      - app

    ports:
      - "443:443"

volumes:
  postgres_data: